# Generated by Django 2.1.7 on 2019-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('cx', 'Chờ xác định'), ('dx', 'Đã xác nhận'), ('dg', 'Đã gửi đi'), ('h', 'Hủy')], default='cx', max_length=2)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('mobile_phone',)},
        ),
    ]
